# -*- coding: utf-8 -*-
"""Aula 3 de pyhton

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRVFIyrqnqaZCYApZIhRsVuG_Bw_7cZp

##Aula 3
"""

numeros = [1,2,3,4,5]
for numeros in numeros:
  print("%f Camiseta: {numeros}")

print(type(numeros))

numero = int(input("Digite um numero(ou 0 para sair): "))

while numero !=0:
  if numero % 2 == 0:
    print("O numero é par.")
  else:
    print("O numero é impar.")

numero = int(input("Digite um numero(ou 0 para sair): "))

for x in range(1,15,3):
  print(x)

filmes = ["1", "2", "3", "4", "5"]

print("Bem vindo a classificação do filme")
print("Você tem cinco filmes para classificar")
print("Digite '0' a qualquer momento para parar.\n")

for filme in filmes:
    classificacao = input(f"Como você classifica o filme '{filme}' de 1 a 5 (ou 0 para parar): ")

    if classificacao == '0':
        print("Que pena")
        break

    classificacao = int(classificacao)

    if classificacao < 1 or classificacao > 5:
        print("Nota inválida")
    else:
        print(f"Você classificou o filme '{filme}' com {classificacao} estrelas.\n")

print("Obrigado")

