# -*- coding: utf-8 -*-
"""Aula 4 de python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHSXmWdA5R-o5ha1CkJPKT0ALz4HQ9eq

##Aula 4
"""

numero = [1,2,3,4,5]

comprimento = len(numero)

comprimento

range(5)

def soma(a,b):
  resultado = a - b
  return resultado

resultado_soma = soma(5,6)

print(resultado_soma)

def e_par(numero):
  if numero % 2 ==0:
    return True
  else:
    return False

numero = 2213516546513515151516541

teste = e_par(numero)

print(teste)

media = 7.12456
arrendondar_media = lambda media: round(media,2)

media_arredonda = arrendondar_media(media)
print(media_arredonda)

nome = input("Digite seu nome: ")

nota_1 = int(input("DIGITE A PRIMEIRA NOTA: "))
nota_2 = int(input("DIGITE A SEGUNDA NOTA: "))
nota_3 = int(input("DIGITE A TERCEIRA NOTA: "))
nota_4 = int(input("DIGITE A QUARTA NOTA: "))

calcular_media = lambda n1, n2, n3, n4: (n1 + n2 + n3 + n4) / 4


media = calcular_media(nota_1, nota_2, nota_3, nota_4)

if media >= 5:
    situacao = "Aprovado"
else:
    situacao = "Reprovado"


print(f"\nAluno: {nome}")
print(f"Média: {media}")
print(f"Situação: {situacao}")

