# -*- coding: utf-8 -*-
"""Aula 01 python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSYGjR_OZAVi-9B6CkkmM8q6F_5j5a3C

##Aula1
"""

print("hello word")

#2. criando variaveis
x = 10
nome = 'gabi'
nota = 8.75
fez_inscriçao = True

print(x)
print(nome)
print(nota)
print(fez_inscriçao)

print(type(x))
print(type(nota))
print(type(nome))
print(type(fez_inscriçao))

nome = input("Digite seu nome:")

print(f"ola{nome}, bem vindo a disciplina de programação" )

nota_1 = int(input("DIGITE A PRIMEIRA NOTA: "))
nota_2 = int(input("DIGITE A SEGUNDA NOTA: "))
nota_3 = int(input("DIGITE A TERCEIRA NOTA: "))
nota_4 = int(input("DIGITE A QUARTA NOTA: "))

media = (nota_1+nota_2+nota_3+nota_4)/4

print(media)

if media <= 5:
  situacao = "Aprovado"
else:
  situacao = " Reprovado"

print(situacao)

