# -*- coding: utf-8 -*-
"""aula 5 de puthon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15A7tnpZbInI2f4xIwf7QhrKC_OH1tars

##AULA 5
"""

def calcular_desconto(valor, percentual):
  if percentual < 0 or percentual > 100:
    return None
  desconto = valor * (percentual/100)
  return valor - desconto

def registar_venda(produto, valor_final):
  print(f">> Venda registrada: {produto} por R$ {valor_final:.2f}")

arrendondar = lambda v: round(v,2)

total_vendas = 0
qtd_vendas = 0

while True:
    print("\n----- minha loja ----- pdv")
    print("1 - Registrar venda")
    print("2 - Ver relatorio do dia")
    print("3 - Encerrar caixa")

    opcao = input("Escolha uma opção: ")

    if opcao == "3":
        print("Encerrando o caixa, até amanhã")
        break

    elif opcao == "1":
        produto = input("Nome do produto: ")
        valor = float(input("Valor do produto: R$ "))
        percentual = float(input("Desconto (%): "))

        valor_final = calcular_desconto(valor, percentual)

        if valor_final is None:
            print("Desconto inválido! Use um valor entre 0 e 100")
        else:
            valor_final = arrendondar(valor_final)
            registar_venda(produto, valor_final)
            total_vendas = total_vendas + valor_final
            qtd_vendas = qtd_vendas + 1

    elif opcao == "2":
        print(f"\nVendas hoje: {qtd_vendas}")
        print(f"Total faturado: R$ {arrendondar(total_vendas)}")

    else:
        print("Opção inválida. Tente novamente")

