# -*- coding: utf-8 -*-
"""AULA 2 de python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2bQWcAbIqEqmdR9lONpwHQKnjcgYkqR

##AULA 2
"""

idade = 10
e_maior_de_idade = idade >=17
print(e_maior_de_idade)

print(True and True)

print(False and True)

idade = int(input("Digite sua idade:"))
if idade < 18:
  print("Menor de idade")
elif idade >= 18 and idade <65:
  print("Adulto")
else:
  print("Idoso")

idade = int(input("Digite sua idade:"))
if idade < 12:
  print("Recomendamos o filme infantil 1")
elif idade >= 12 and idade <18:
  print("Recomendamos o filme infantil 2")
else:
  print("Recomendamos o filme infantil 3")

quantidade_de_ingresso = 10
if quantidade_de_ingresso > 0:
  print("Ingresso disponiveis. Divirta-se no cinema")
else:
  print("Desculpe, todos os ingressos estão esgotados")

idade = int(input("Digite sua idade: "))
quantidade_de_ingresso = 10

if idade < 12:
    filme = "Filme infantil 1"
elif idade >= 12 and idade < 18:
    filme = "Filme infantil 2"
else:
    filme = "Filme infantil 3"

quantidade_pedida = int(input("Quantos ingressos você deseja? "))

print("Filme recomendado:", filme)

if quantidade_pedida <= quantidade_de_ingresso:
    print("Ingressos disponíveis. Divirta-se no cinema!")
else:
    print("Desculpe, não temos essa quantidade de ingressos disponível.")

